### ISSUE TITLE
attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by BugReportering** [runsy/climatez#1]
**2021-03-23 07:39:33: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'climatez' in callback environment_Step(): ...me/minetest/minetest/bin/../mods/climatez/engine.lua:575: attempt to index field '?' (a nil value)
2021-03-23 07:39:33: ERROR[Main]: stack traceback:
2021-03-23 07:39:33: ERROR[Main]: 	...me/minetest/minetest/bin/../mods/climatez/engine.lua:575: in function '?'
2021-03-23 07:39:33: ERROR[Main]: 	...e/minetest/minetest/bin/../builtin/game/register.lua:422: in function <...e/minetest/minetest/bin/../builtin/game/register.lua:406>
2021-03-23 07:39:33: ERROR[Main]: stack traceback:**

### **Minetest server info:** 
```
Minetest 5.4.0 (Linux)
Using Irrlicht 1.8.4
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
```

**Comment by BugReportering** [comment]
Please fix soon, it's continually crashing my server.  I don't want to have to remove the Climatez mod because it adds enjoyment to the game.  Thank you for your time in creating this mod, improving, and bug fixing.

**Comment by runsy** [comment]
Ok. Check the last version.

**Comment by BugReportering** [comment]
Thanks for a quick response.  Checking now.  Will be a little bit before I report back, it doesn't crash right off when it was crashing.  Once I'm sure it's no longer crashing, or otherwise, I'll report back.

**Comment by BugReportering** [comment]
Has been good for 1 hour.  Seems fixed. Thank you very much.
